name: Build and Deploy Self-Hosted

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # - name: Checkout source
      #   uses: actions/checkout@v4
      #   with:
      #     clean: false

      - name: Prepare source
        run: |
          echo "Using local repo source (no checkout needed)"


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test BuildWebApp.Tests/BuildWebApp.Tests.csproj --collect:"XPlat Code Coverage" --results-directory TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      - name: Publish app
        run: dotnet publish BuildWebApp/BuildWebApp.csproj -c Release -o ./publish

      - name: Deploy locally
        run: |
          $deployPath = "C:\inetpub\wwwroot\BuildWebApp"
          if (Test-Path $deployPath) {
            Remove-Item $deployPath -Recurse -Force
          }
          New-Item -ItemType Directory -Path $deployPath | Out-Null
          Copy-Item -Path ./publish/* -Destination $deployPath -Recurse -Force
          Write-Host "App deployed to $deployPath"

      - name: Run application
        run: |
          Start-Process "C:\inetpub\wwwroot\BuildWebApp\BuildWebApp.exe"
