name: Build Web App

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - id: build
        name: Build
        run: dotnet build --no-restore

      - id: test
        if: steps.build.outcome == 'success'
        name: Test with Coverage
        run: dotnet test "BuildWebApp.Tests/BuildWebApp.Tests.csproj" --collect:"XPlat Code Coverage" --results-directory TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      - name: Debug TestResults
        run: |
          Write-Host "Listing TestResults directory:"
          Get-ChildItem -Recurse TestResults -ErrorAction SilentlyContinue
          Write-Host "Searching for cobertura files:"
          Get-ChildItem -Recurse -Filter *.cobertura.xml

      - name: Code Coverage Summary (Windows)
        run: |
          $coverageFiles = Get-ChildItem -Recurse -Filter *.cobertura.xml
          if ($coverageFiles.Count -eq 0) {
              Write-Host "No coverage files found."
              exit 0
          }
      
          foreach ($file in $coverageFiles) {
              Write-Host "Coverage file: $($file.FullName)"
          }
      
          Write-Host "You can use ReportGenerator (dotnet tool) to generate a readable summary."


      - id: publish
        name: Publish
        run: dotnet publish BuildWebApp/BuildWebApp.csproj -c Release -o published --self-contained -r win-x64 /p:UseAppHost=true


      - name: Zip Artifact
        run: Compress-Archive -Path published\* -DestinationPath app.zip

      - id: upload
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-webapp
          path: app.zip

      - id: deploy
        name: Deploy & Run as Windows Service (Self-Host)
        shell: powershell
        run: |
          # Deployment folder
          $deployDir = "$env:USERPROFILE\BuildWebApp_deploy"
          if (!(Test-Path $deployDir)) { New-Item -ItemType Directory -Path $deployDir }

          # Copy published files
          Write-Host "Copying published files to $deployDir..."
          Copy-Item -Path ".\published\*" -Destination $deployDir -Recurse -Force

          # Stop and delete existing service if exists
          try { sc.exe stop BuildWebAppService 2>$null } catch {}
          try { sc.exe delete BuildWebAppService 2>$null } catch {}

          # DLL path
          $dllPath = Join-Path $deployDir "BuildWebApp.dll"

          # Full path to dotnet.exe
          $dotnetExe = "C:\Program Files\dotnet\dotnet.exe"

          # Properly quoted binPath
          $binPath = "`"$dotnetExe`" `"$dllPath`" --urls http://0.0.0.0:5000"
          Write-Host "Creating Windows Service for BuildWebApp..."
          sc.exe create BuildWebAppService binPath= "$binPath" start= auto

          # Start the service
          sc.exe start BuildWebAppService

          Write-Host "Deployment complete. App is running as a Windows Service on http://localhost:5000"








