name: Build Web App

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        
      - name: Restore dependencies
        run: dotnet restore

      - id: build
        name: Build
        run: dotnet build --no-restore

      - id: test
        if: steps.build.outcome == 'success'
        name: Test with Coverage
        run: dotnet test "BuildWebApp.Tests/BuildWebApp.Tests.csproj" \
               --collect:"XPlat Code Coverage" \
               --results-directory TestResults \
               -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      - name: Debug TestResults
        run: |
          echo "Listing TestResults directory:"
          ls -R TestResults || echo "No TestResults directory found"
          echo "Searching for cobertura files:"
          find . -name "*.cobertura.xml" || echo "No cobertura files found"

      - id: coverage
        name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TestResults/**/coverage.cobertura.xml
          badge: false
          fail_below_min: false
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: console
