name: Build and Run on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install .NET into a user-writable folder (C:\dotnet)
      # - name: Set up .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '8.0.x'
      #     install-dir: C:\dotnet

      # Add .NET install dir to PATH
      - name: Add .NET to PATH
        run: echo "C:\dotnet" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the app
        run: dotnet build --configuration Release --no-restore

      - name: Run the app
        run: dotnet run --configuration Release --project ./YourProjectName/YourProjectName.csproj
