name: Build Web App

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - id: build
        name: Build
        run: dotnet build --no-restore

      - id: test
        if: steps.build.outcome == 'success'
        name: Test with Coverage
        run: dotnet test "BuildWebApp.Tests/BuildWebApp.Tests.csproj" --collect:"XPlat Code Coverage" --results-directory TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      - name: Debug TestResults
        run: |
          Write-Host "Listing TestResults directory:"
          Get-ChildItem -Recurse TestResults -ErrorAction SilentlyContinue
          Write-Host "Searching for cobertura files:"
          Get-ChildItem -Recurse -Filter *.cobertura.xml

      - name: Code Coverage Summary (Windows)
        run: |
          $coverageFiles = Get-ChildItem -Recurse -Filter *.cobertura.xml
          if ($coverageFiles.Count -eq 0) {
              Write-Host "No coverage files found."
              exit 0
          }
      
          foreach ($file in $coverageFiles) {
              Write-Host "Coverage file: $($file.FullName)"
          }
      
          Write-Host "You can use ReportGenerator (dotnet tool) to generate a readable summary."


      - id: publish
        name: Publish
        run: dotnet publish BuildWebApp/BuildWebApp.csproj -c Release -o published --self-contained -r win-x64 /p:UseAppHost=true


      - name: Zip Artifact
        run: Compress-Archive -Path published\* -DestinationPath app.zip

      - id: upload
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-webapp
          path: app.zip

      - id: deploy
        name: Deploy using nssm (Fixed Download)
        run: |
          $serviceName = "BuildWebApp"
          $deployDir = "$env:USERPROFILE\BuildWebApp_deploy"
          
          # Download nssm with proper error handling
          $nssmDir = "$env:TEMP\nssm"
          $nssmExe = "$nssmDir\nssm.exe"
          
          if (!(Test-Path $nssmExe)) {
              Write-Host "Downloading nssm..."
              
              # Create temp directory
              if (Test-Path $nssmDir) {
                  Remove-Item $nssmDir -Recurse -Force -ErrorAction SilentlyContinue
              }
              New-Item -ItemType Directory -Path $nssmDir -Force
              
              # Download nssm from reliable source
              $nssmUrl = "https://nssm.cc/release/nssm-2.24.zip"
              $nssmZip = "$env:TEMP\nssm.zip"
              
              try {
                  # Download with progress
                  Invoke-WebRequest -Uri $nssmUrl -OutFile $nssmZip -UserAgent "PowerShell"
                  Write-Host "Download completed successfully"
                  
                  # Extract nssm
                  Expand-Archive -Path $nssmZip -DestinationPath $nssmDir -Force
                  Write-Host "Extraction completed"
                  
                  # Find nssm.exe in the extracted files
                  $nssmExe = Get-ChildItem -Path $nssmDir -Recurse -Filter "nssm.exe" | Select-Object -First 1 -ExpandProperty FullName
                  
                  if (!$nssmExe) {
                      Write-Host "Looking for nssm.exe in extracted files..."
                      Get-ChildItem -Path $nssmDir -Recurse | Format-Table Name, FullName
                      throw "nssm.exe not found in downloaded archive"
                  }
                  
                  Write-Host "Found nssm.exe at: $nssmExe"
                  
              } catch {
                  Write-Host "Failed to download nssm: $($_.Exception.Message)"
                  Write-Host "Trying alternative download method..."
                  
                  # Alternative download method
                  try {
                      $webClient = New-Object System.Net.WebClient
                      $webClient.DownloadFile($nssmUrl, $nssmZip)
                      Expand-Archive -Path $nssmZip -DestinationPath $nssmDir -Force
                      $nssmExe = Get-ChildItem -Path $nssmDir -Recurse -Filter "nssm.exe" | Select-Object -First 1 -ExpandProperty FullName
                  } catch {
                      Write-Host "Alternative download also failed: $($_.Exception.Message)"
                      # Fallback to direct executable download
                      $nssmExe = "$nssmDir\nssm.exe"
                      $directUrl = "https://nssm.cc/ci/nssm-2.24-101-g897c7ad.zip"
                      Invoke-WebRequest -Uri $directUrl -OutFile $nssmZip
                      Expand-Archive -Path $nssmZip -DestinationPath $nssmDir -Force
                      $nssmExe = Get-ChildItem -Path $nssmDir -Recurse -Filter "nssm.exe" | Select-Object -First 1 -ExpandProperty FullName
                  }
              }
          }
          
          # Verify nssm.exe exists
          if (!(Test-Path $nssmExe)) {
              Write-Host "nssm.exe still not found. Available files:"
              Get-ChildItem -Path $nssmDir -Recurse -ErrorAction SilentlyContinue | Format-Table Name, FullName
              throw "nssm.exe could not be downloaded or found"
          }
          
          Write-Host "Using nssm from: $nssmExe"
          
          # Clean and deploy application
          if (Test-Path $deployDir) { 
              Write-Host "Cleaning deployment directory..."
              Remove-Item "$deployDir\*" -Recurse -Force -ErrorAction SilentlyContinue 
          } else { 
              New-Item -ItemType Directory -Path $deployDir -Force 
          }
          
          Write-Host "Copying published files..."
          Copy-Item -Path ".\published\*" -Destination $deployDir -Recurse -Force
          
          # Stop and remove existing service
          Write-Host "Stopping and removing existing service..."
          & $nssmExe stop $serviceName -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 3
          & $nssmExe remove $serviceName confirm -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 2
          
          # Install with nssm - using the EXE file directly
          $exePath = Join-Path $deployDir "BuildWebApp.exe"
          
          if (!(Test-Path $exePath)) {
              Write-Host "ERROR: BuildWebApp.exe not found at $exePath"
              Write-Host "Available files in deployment directory:"
              Get-ChildItem $deployDir | Format-Table Name, Length
              throw "Application executable not found"
          }
          
          Write-Host "Installing service with nssm..."
          & $nssmExe install $serviceName $exePath "--urls http://0.0.0.0:5000"
          
          if ($LASTEXITCODE -ne 0) {
              throw "Failed to install service with nssm. Exit code: $LASTEXITCODE"
          }
          
          # Configure nssm service settings
          Write-Host "Configuring service settings..."
          & $nssmExe set $serviceName DisplayName "Build Web App"
          & $nssmExe set $serviceName Description "Build Web Application Service"
          & $nssmExe set $serviceName Start SERVICE_AUTO_START
          & $nssmExe set $serviceName AppDirectory $deployDir
          & $nssmExe set $serviceName AppStdout "$deployDir\service.log"
          & $nssmExe set $serviceName AppStderr "$deployDir\service_error.log"
          & $nssmExe set $serviceName AppRotateFiles 1
          & $nssmExe set $serviceName AppRotateOnline 1
          & $nssmExe set $serviceName AppRotateSeconds 86400
          & $nssmExe set $serviceName AppRotateBytes 1048576
          
          # Set service to restart on failure
          & $nssmExe set $serviceName AppExit Default Restart
          & $nssmExe set $serviceName AppThrottle 15000
          
          # Start service
          Write-Host "Starting service..."
          & $nssmExe start $serviceName
          
          if ($LASTEXITCODE -ne 0) {
              Write-Host "WARNING: Service start returned exit code: $LASTEXITCODE"
          }
          
          # Wait and check status
          Start-Sleep -Seconds 5
          $service = Get-Service $serviceName -ErrorAction SilentlyContinue
          
          if ($service -and $service.Status -eq 'Running') {
              Write-Host "SUCCESS: Service is running with nssm!"
              
              # Test the application
              Start-Sleep -Seconds 3
              try {
                  $response = Invoke-RestMethod -Uri "http://localhost:5000" -TimeoutSec 10 -ErrorAction SilentlyContinue
                  Write-Host "Service is responding on port 5000"
              } catch {
                  Write-Host "Service might be starting... check logs in: $deployDir\service.log"
              }
              
              # Show recent logs
              if (Test-Path "$deployDir\service.log") {
                  Write-Host "=== Recent Service Logs ==="
                  Get-Content "$deployDir\service.log" -Tail 10 -ErrorAction SilentlyContinue
              }
          } else {
              Write-Host "Service status: $($service.Status)"
              Write-Host "Checking service logs..."
              
              if (Test-Path "$deployDir\service_error.log") {
                  Write-Host "=== Service Error Logs ==="
                  Get-Content "$deployDir\service_error.log" -ErrorAction SilentlyContinue
              }
              
              if (Test-Path "$deployDir\service.log") {
                  Write-Host "=== Service Logs ==="
                  Get-Content "$deployDir\service.log" -ErrorAction SilentlyContinue
              }
          }
          
          Write-Host "Deployment process completed."